name: myapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  fl_chart: ^1.1.1
  provider: ^6.1.5+1
  uuid: ^4.5.1
  flutter_staggered_animations: ^1.1.1
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  google_fonts: ^6.3.2
  flutter_colorpicker: ^1.1.0
  flutter_iconpicker: ^4.0.3
  bottom_navy_bar: ^6.1.0
  ultimate_bottom_navbar: ^0.0.7

  google_mobile_ads: ^5.0.0


  # Added for SVG icons (vector icons inside the app)
  flutter_svg: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # launcher icons generator (already present)
  flutter_launcher_icons: "^0.14.4"

  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13

# flutter_launcher_icons config (root-level) â€” used by flutter_launcher_icons package
flutter_launcher_icons:
  android: true
  # ios: true
  image_path: "assets/icons/icon.png"
  # If you want Android adaptive icons later, replace above with adaptive_icon block:
  # adaptive_icon:
  #   foreground_image: "assets/icons/foreground.png"
  #   background_image: "assets/icons/background.png"

flutter:
  uses-material-design: true

  fonts:
    - family: ClashGrotesk
      fonts:
        - asset: assets/fonts/ClashGrotesk-Extralight.otf
          weight: 200
        - asset: assets/fonts/ClashGrotesk-Light.otf
          weight: 300
        - asset: assets/fonts/ClashGrotesk-Regular.otf
          weight: 400
        - asset: assets/fonts/ClashGrotesk-Medium.otf
          weight: 500
        - asset: assets/fonts/ClashGrotesk-Semibold.otf
          weight: 600
        - asset: assets/fonts/ClashGrotesk-Bold.otf
          weight: 700



  assets:
    - assets/logo.png
    - assets/icons/        # include all files in the icons folder (png/svg/foreground/background etc.)
    - assets/fonts/
